### PR TITLE
Fixed Typo

### PR DESCRIPTION
**Pull request by Zeitungsleser**

### CODE REVIEW

**Comment by boldt** [comment]
@gluap

**Comment by gluap** [comment]
Actually this isn't a typo but a [function literal](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/User-Defined_Functions_and_Modules). Maybe you're trying to run this on an older OpenSCAD Version?

**Comment by Zeitungsleser** [comment]
Thanks @gluap. I found the section on the wikibook, but I don't see, how it's a difference in this example. The error occurred, cause in apt-get, the newest version in 2019.05. But now I tried installing via snap and I got the right version.

**Comment by boldt** [comment]
Can we specify a minimal version for Openscad?

**Comment by gluap** [comment]
@boldt makes sense - for me this is the first time I realized that we use newer openscad features.

**Pull request closed without merging**
